name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  scrap_articles:
    name: Generate article JSON from DW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install project and dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install bs4 requests
          export
      
      - name: Generate predictions
        shell: bash
        run: |
          python fetch_article.py

      - uses: actions/upload-artifact@main
        with:
          name: article_data
          path: dw_articles.json

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [scrap_articles]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download article data
        uses: actions/download-artifact@main
      
      - name: Move article data to public
        shell: bash
        run: |
          ls
          mv article_data/dw_articles.json public/dw_articles.json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4